# Generated by Django 3.0.6 on 2020-07-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(default='none', max_length=100)),
                ('email', models.CharField(default='none', max_length=100)),
                ('age', models.CharField(default='none', max_length=100)),
                ('mobile', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
